name: Release

on:
  push:
    tags: ["v*"]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Read package.json node and npm engines version
      uses: skjnldsv/read-package-engines-version-actions@v1.2
      id: versions
      with:
        fallbackNode: '^12'
        fallbackNpm: '^6'

    - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.versions.outputs.nodeVersion }}
    - name: Build app
      run: make appstore
    - name: "Create release"
      run: |
        set -x
        make appstore
        mv build/artifacts/appstore/nextcloud-secrets.tar.gz ./secrets.tar.gz
        tag_name="${GITHUB_REF##*/}"
        hub release create -a secrets.tar.gz -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

