# SPDX-FileCopyrightText: Tobias Knöppler <thecalcaholic@web.de>
# SPDX-License-Identifier: GPL-3.0-or-later

name: Release

on:
  push:
    tags:
      - "v*"
      - "test*"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: secrets
    - name: enter repository
      run: |
        cd secrets
        ls -l ..
    - name: Read package.json node and npm engines version
      uses: skjnldsv/read-package-engines-version-actions@v1.2
      id: versions
      with:
        fallbackNode: '^12'
        fallbackNpm: '^6'

    - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.versions.outputs.nodeVersion }}
    - name: Build app
      run: make appstore
    - name: "Create release"
      run: |
        set -x
        make appstore
        mv build/artifacts/appstore/secrets.tar.gz ./secrets.tar.gz
        sha256sum secrets.tar.gz > secrets.sha256
        tag_name="${GITHUB_REF##*/}"
        hub release create -a secrets.tar.gz -a secrets.sha256 -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

